
insert into po_customer (customer_name, customer_code, category, address, place) values ('Reallinks', '820', 'C', '45461 Oriole Hill', 'Bang Rakam');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Midel', '520', 'D', '41 Talisman Point', 'Nizhniy Lomov');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Shufflester', '520', 'D', '83451 Johnson Road', 'Poitiers');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Linkbridge', '620', 'A', '6 Loomis Pass', 'Ticrapo');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Leexo', '620', 'A', '6876 Sheridan Avenue', 'Vityazevo');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Miboo', '920', 'D', '11102 Monica Avenue', 'Marseille');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Trudeo', '820', 'C', '63652 Rutledge Trail', 'Andalan');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Fivebridge', '120', 'D', '5573 Steensland Avenue', 'Santa Maria');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Thoughtstorm', '320', 'D', '435 Dunning Road', 'La Libertad');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Brightbean', '320', 'C', '525 Pankratz Junction', 'Shenzhengqiao');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Brainverse', '220', 'A', '24 Muir Park', 'Frankfurt am Main');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Meedoo', '020', 'D', '75169 Judy Junction', 'Washington');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Yata', '420', 'C', '175 Ramsey Avenue', 'Faeanak Dua');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Omba', '320', 'D', '7 Clemons Drive', 'Dundee');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Dabtype', '220', 'C', '4 Kenwood Lane', 'Cabanas');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Gabvine', '320', 'D', '00 Oneill Pass', 'Ciudad Choluteca');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Yodoo', '420', 'D', '7237 Springs Terrace', 'Anolaima');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Trunyx', '220', 'A', '302 Brentwood Junction', 'Zhuhe');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Skyndu', '420', 'D', '23 Emmet Junction', 'Głuchołazy');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Mybuzz', '120', 'D', '243 Mariners Cove Drive', 'Lakshmīpur');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Quinu', '220', 'D', '20305 Hayes Junction', 'Zongga');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Rhynoodle', '020', 'B', '2058 Kensington Drive', 'Borgo Maggiore');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Buzzshare', '620', 'C', '7798 Hallows Way', 'São João');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Zava', '020', 'C', '2672 Golf Course Alley', 'Ágio Pnévma');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Meezzy', '620', 'B', '32 Sundown Pass', 'Ciomas');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Demizz', '320', 'D', '48 Mcguire Avenue', 'Rebe');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Avamm', '020', 'D', '7100 Burrows Hill', 'Viejo Daan Banua');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Mybuzz', '320', 'D', '315 Bayside Drive', 'Raškovice');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Bubbletube', '420', 'C', '05111 Old Gate Court', 'Rybie');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Tagchat', '820', 'C', '18 4th Court', 'Chum Phuang');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Jayo', '320', 'C', '848 Forest Run Circle', 'Vergara');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Realfire', '720', 'C', '905 Green Plaza', 'Không');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Quatz', '520', 'B', '28383 Aberg Court', 'Huangtan');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Voonix', '120', 'D', '417 Springs Circle', 'Haicheng');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Kazio', '020', 'D', '25 Quincy Street', 'Malaba');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Topiclounge', '220', 'C', '55415 Forest Dale Pass', 'Al Majāridah');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Voolith', '520', 'D', '986 Cardinal Alley', 'Domaradz');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Voolith', '320', 'D', '13199 Golf View Junction', 'Pontes');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Mudo', '820', 'B', '45237 Hoffman Trail', 'Diapaga');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Meevee', '320', 'D', '00516 Crest Line Way', 'Losari');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Tazz', '520', 'D', '56572 Hoffman Parkway', 'Curpahuasi');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Plajo', '520', 'D', '06 Meadow Vale Way', 'Beyla');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Kwideo', '220', 'A', '94496 Waubesa Drive', 'Libei');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Zooveo', '720', 'B', '8374 Elgar Lane', 'Uticyacu');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Omba', '720', 'C', '2072 Trailsway Junction', 'Wolmaransstad');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Photospace', '220', 'D', '666 Carey Plaza', 'Rabāţ-e Sangī-ye Pā’īn');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Shuffletag', '820', 'D', '72856 8th Parkway', 'Paço');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Skimia', '320', 'C', '30 Bellgrove Park', 'Nagarakembang');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Youopia', '520', 'C', '416 Anthes Hill', 'Hongguang');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Browsetype', '120', 'A', '470 Prairie Rose Pass', 'Pyinmana');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Babblestorm', '720', 'B', '1478 Duke Circle', 'Tartaro');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Trudeo', '620', 'A', '6139 Crownhardt Court', 'Bảo Lộc');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Browsecat', '420', 'D', '4256 Ridge Oak Center', 'Moravská Nová Ves');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Kwilith', '220', 'D', '244 Merchant Avenue', 'Hongqiao');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Camimbo', '020', 'A', '51 Waywood Parkway', 'Miami');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Yakidoo', '720', 'D', '829 Shasta Center', 'Bilüü');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Zoonoodle', '120', 'D', '84923 Northfield Place', 'Concepción del Bermejo');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Photobean', '820', 'D', '8163 Rutledge Lane', 'Dorchester');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Roomm', '520', 'C', '361 Lukken Trail', 'Xicheng');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Snaptags', '820', 'B', '9470 Cherokee Plaza', 'Loandjili');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Photojam', '520', 'A', '46 Summit Center', 'San Diego');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Skinte', '720', 'D', '32341 Di Loreto Trail', 'Santo Antônio de Posse');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Livepath', '220', 'A', '0378 Banding Court', 'Lukavec');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Jetpulse', '720', 'D', '296 Fieldstone Way', 'Syzran’');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Kazio', '820', 'D', '0544 Sage Junction', 'Bruxelles');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Livetube', '820', 'D', '85995 Talmadge Road', 'Polowat');
insert into po_customer (customer_name, customer_code, category, address, place) values ('Dabtype', '320', 'C', '2641 Becker Lane', 'Malaryta');