# Generated by Django 4.1.1 on 2022-10-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, unique=True)),
                ('customer_code', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_po_number', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(verbose_name='P.O. Date (yyyy-mm-dd)')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['customer_po_number'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('our_item_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, unique=True)),
                ('unit_type', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_item_code', models.CharField(max_length=255)),
                ('customer_item_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('customer_po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.customerpo')),
            ],
            options={
                'ordering': ['customer_item_code'],
            },
        ),
    ]
