# Generated by Django 4.1.2 on 2022-10-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, unique=True)),
                ('customer_code', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_po_number', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(verbose_name='P.O. Date (yyyy-mm-dd)')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_code', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['customer_po_number'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_po_number', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='P.O. Date (yyyy-mm-dd)')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('dispatch_mail_status', models.CharField(choices=[('EM', 'Emailed'), ('NM', 'Not Emailed')], max_length=10)),
                ('docket', models.CharField(max_length=255)),
                ('parcel', models.CharField(choices=[('PAR', 'PARCEL'), ('CHA', 'CHALLAN'), ('CHQ', 'CHEQUE'), ('DEN', 'DEBIT NOTE'), ('DOC', 'DOCUMENTS'), ('FBL', 'FREIGHT BILL'), ('NDC', 'NDC'), ('OBL', 'ORIGINAL BILL'), ('VFM', 'VENDOR FORM'), ('CFM', 'C-FORM')], max_length=10)),
                ('dimension', models.CharField(max_length=255)),
                ('charged_weight', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('unit', models.CharField(choices=[('1', 'BAG'), ('2', 'BAL'), ('3', 'BDL'), ('4', 'BKL'), ('5', 'BOU'), ('6', 'BOX'), ('7', 'BTL'), ('8', 'BUN'), ('9', 'CAN'), ('10', 'CBM'), ('11', 'CCM'), ('12', 'CMS'), ('13', 'CTN'), ('14', 'DOZ'), ('15', 'DRM'), ('16', 'GGR'), ('17', 'GMS'), ('18', 'GRS'), ('19', 'GYD'), ('20', 'KGS'), ('21', 'KLR'), ('22', 'KME'), ('23', 'MLT'), ('24', 'MTR'), ('25', 'MTS'), ('26', 'NOS'), ('27', 'PAC'), ('28', 'PCS'), ('29', 'PRS'), ('30', 'QTL'), ('31', 'ROL'), ('32', 'SET'), ('33', 'SQF'), ('34', 'SQM'), ('35', 'SQY'), ('36', 'TBS'), ('37', 'TGM'), ('38', 'THD'), ('39', 'TON'), ('40', 'TUB'), ('41', 'UGS'), ('42', 'UNT'), ('43', 'YDS'), ('44', 'OTH')], max_length=10)),
                ('curior_company', models.CharField(choices=[('1', 'DTDC'), ('2', 'By Hand'), ('3', 'Gati'), ('4', 'Gaurav Transport'), ('5', 'Blue Dart'), ('6', 'Delhi Sonipat'), ('7', 'FedEx'), ('8', 'HKS Transport'), ('9', 'Inland'), ('10', 'Professional'), ('11', 'Shree Maruti'), ('12', 'TCI Express'), ('13', 'Tempo'), ('14', 'Trackon'), ('15', 'VRL'), ('16', 'DAKSH LOGISTICS'), ('17', 'The Bharat Motor Transport'), ('18', 'By Metro'), ('19', 'Samay Shatabdi Travels'), ('20', 'Satellitte cargo'), ('21', 'Aash Logistics'), ('22', 'Speed Post'), ('23', 'Delhi Rudarpur sitarganj Goods'), ('24', 'Bombay Barelly Goods Carriers'), ('25', 'Delhi Modi Transport'), ('26', 'Associat Road Carrier'), ('27', 'Spoton logistics'), ('28', 'Pooja Transport'), ('29', 'Dexters Logistics pvt ltd'), ('30', 'Om logistics'), ('31', 'RSC LOGISTICS'), ('32', 'Bom gim Courier'), ('33', 'Delivery'), ('34', 'ECOM Express'), ('35', 'XpressBee'), ('36', 'Sugam Parivahan'), ('37', 'TCI FREIGHT'), ('38', 'HELLO Courier'), ('39', 'Khullar tempo'), ('40', 'Surjit Singh Tempo Service'), ('41', 'SAFEEXPRESS'), ('42', 'Tirupati Courier'), ('43', 'Accurate freight carriers'), ('44', 'The Bharat Motor Transport'), ('45', 'Porter')], max_length=10)),
                ('sender', models.CharField(blank=True, choices=[('01', 'ARUSH'), ('02', 'ARUSH LLP'), ('03', 'ARNAV')], max_length=10, null=True)),
                ('delivery_status', models.CharField(choices=[('DL', 'DELIVERED'), ('ND', 'NOT DELIVERED'), ('RE', 'RETURNED')], max_length=10)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='P.O. Date (yyyy-mm-dd)')),
                ('invoice_status', models.CharField(choices=[('IN', 'Invoiced'), ('NI', 'Not Invoiced')], max_length=10)),
                ('insurance', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('asn_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('our_item_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, unique=True)),
                ('unit_type', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='VendorPo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_po_number', models.CharField(max_length=100)),
                ('our_po_number', models.CharField(max_length=100, unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('po_date', models.DateField(verbose_name='P.O. Date (yyyy-mm-dd)')),
                ('acknowledgement_date', models.DateField(blank=True, null=True, verbose_name='Acknowledgement Date (yyyy-mm-dd)')),
            ],
            options={
                'ordering': ['po_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_item_code', models.CharField(max_length=255)),
                ('customer_item_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('1', 'BAG'), ('2', 'BAL'), ('3', 'BDL'), ('4', 'BKL'), ('5', 'BOU'), ('6', 'BOX'), ('7', 'BTL'), ('8', 'BUN'), ('9', 'CAN'), ('10', 'CBM'), ('11', 'CCM'), ('12', 'CMS'), ('13', 'CTN'), ('14', 'DOZ'), ('15', 'DRM'), ('16', 'GGR'), ('17', 'GMS'), ('18', 'GRS'), ('19', 'GYD'), ('20', 'KGS'), ('21', 'KLR'), ('22', 'KME'), ('23', 'MLT'), ('24', 'MTR'), ('25', 'MTS'), ('26', 'NOS'), ('27', 'PAC'), ('28', 'PCS'), ('29', 'PRS'), ('30', 'QTL'), ('31', 'ROL'), ('32', 'SET'), ('33', 'SQF'), ('34', 'SQM'), ('35', 'SQY'), ('36', 'TBS'), ('37', 'TGM'), ('38', 'THD'), ('39', 'TON'), ('40', 'TUB'), ('41', 'UGS'), ('42', 'UNT'), ('43', 'YDS'), ('44', 'OTH')], max_length=10)),
                ('customer_po_id', models.ForeignKey(db_column='customer_po_number', on_delete=django.db.models.deletion.CASCADE, to='po.customerpo')),
            ],
            options={
                'ordering': ['customer_po_id'],
            },
        ),
    ]
