# Generated by Django 4.1.2 on 2022-10-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='customer_po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.customerpo'),
        ),
    ]
