# Generated by Django 4.1.1 on 2022-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
