# Generated by Django 4.1.1 on 2022-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_alter_customerpo_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='place',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
