# Generated by Django 4.1.2 on 2022-10-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_alter_customerpoitem_customer_po_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='customer_po_id',
            field=models.ForeignKey(db_column='customer_po_id', on_delete=django.db.models.deletion.CASCADE, to='po.customerpo'),
        ),
    ]
