# Generated by Django 4.1.1 on 2022-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_alter_customerpo_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
