# Generated by Django 4.1.2 on 2022-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_alter_customerpoitem_customer_po_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoitem',
            name='customer_po_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
