# Generated by Django 4.1.1 on 2022-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_alter_customerpo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
