# Generated by Django 4.1.2 on 2022-10-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_customerpoitem_customer_po_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpoitem',
            old_name='unit',
            new_name='unit_code',
        ),
    ]
