# Generated by Django 4.1.1 on 2022-10-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_alter_customerpo_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='customer_po_number',
            field=models.CharField(max_length=255),
        ),
    ]
