# Generated by Django 4.1.1 on 2022-10-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_alter_customerpoitem_customer_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='customer_po_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.customerpo'),
        ),
    ]
