# Generated by Django 4.1.2 on 2022-10-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_rename_unit_customerpoitem_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoitem',
            name='unit',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
