# Generated by Django 4.1.1 on 2022-10-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_alter_customerpoitem_customer_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='unit',
            field=models.CharField(choices=[('1', 'BAG'), ('2', 'BAL'), ('3', 'BDL'), ('4', 'BKL'), ('5', 'BOU'), ('6', 'BOX'), ('7', 'BTL'), ('8', 'BUN'), ('9', 'CAN'), ('10', 'CBM'), ('11', 'CCM'), ('12', 'CMS'), ('13', 'CTN'), ('14', 'DOZ'), ('15', 'DRM'), ('16', 'GGR'), ('17', 'GMS'), ('18', 'GRS'), ('19', 'GYD'), ('20', 'KGS'), ('21', 'KLR'), ('22', 'KME'), ('23', 'MLT'), ('24', 'MTR'), ('25', 'MTS'), ('26', 'NOS'), ('27', 'PAC'), ('28', 'PCS'), ('29', 'PRS'), ('30', 'QTL'), ('31', 'ROL'), ('32', 'SET'), ('33', 'SQF'), ('34', 'SQM'), ('35', 'SQY'), ('36', 'TBS'), ('37', 'TGM'), ('38', 'THD'), ('39', 'TON'), ('40', 'TUB'), ('41', 'UGS'), ('42', 'UNT'), ('43', 'YDS'), ('44', 'OTH')], max_length=10),
        ),
    ]
