# Generated by Django 4.1.2 on 2022-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_customerpoitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpoitem',
            name='unit_code',
        ),
        migrations.AlterField(
            model_name='customerpoitem',
            name='unit',
            field=models.CharField(choices=[('BAG', 'BAG'), ('BAL', 'BAL'), ('BDL', 'BDL'), ('BKL', 'BKL'), ('BOU', 'BOU'), ('BOX', 'BOX'), ('BTL', 'BTL'), ('BUN', 'BUN'), ('CAN', 'CAN'), ('CBM', 'CBM'), ('CCM', 'CCM'), ('CMS', 'CMS'), ('CTN', 'CTN'), ('DOZ', 'DOZ'), ('DRM', 'DRM'), ('GGR', 'GGR'), ('GMS', 'GMS'), ('GRS', 'GRS'), ('GYD', 'GYD'), ('KGS', 'KGS'), ('KLR', 'KLR'), ('KME', 'KME'), ('MLT', 'MLT'), ('MTR', 'MTR'), ('MTS', 'MTS'), ('NOS', 'NOS'), ('PAC', 'PAC'), ('PCS', 'PCS'), ('PRS', 'PRS'), ('QTL', 'QTL'), ('ROL', 'ROL'), ('SET', 'SET'), ('SQF', 'SQF'), ('SQM', 'SQM'), ('SQY', 'SQY'), ('TBS', 'TBS'), ('TGM', 'TGM'), ('THD', 'THD'), ('TON', 'TON'), ('TUB', 'TUB'), ('UGS', 'UGS'), ('UNT', 'UNT'), ('YDS', 'YDS'), ('OTH', 'OTH')], max_length=10),
        ),
    ]
