# Generated by Django 4.1.2 on 2022-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0007_remove_customerpoitem_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoitem',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
